# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish stable

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.8.0
          registry-url: https://registry.npmjs.org/
      - run: npm clean-install
      # check the licences allow list to avoid incorrectly licensed dependencies creeping in: 
      - run: npm run license-check
      # builds all bundles
      - run: npm run build
      # runs tests in node environment
      - run: npm run test:node
      # Note - this is not required but it gives a clean failure prior to attempting a release if the GH workflow runner is not authenticated with npm.js
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
